services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - ../.env
    # command: ["--host", "0.0.0.0", "--port", "8000", "--workers", "$UVICORN_WORKER_COUNT"]
    command: ["--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata: